### PR TITLE
fix(bmr): validator used few blocks after removal from bsc validator-set

### LINKED ISSUE #575: bug(bmr): validator is used few blocks after removal from bsc validator-set
## Overview
Current implementation of bsc verifier assumes that once the validator-set gets updated in an epoch block, the new set is applicable henceforth. However, it has been seen that validator present in previous epoch can still validate blocks in the current epoch even after its removal specified in epoch block. A previously existing validator is seen to validate blocks early in the epoch e.g. within 4-5 blocks after epoch block.

## Steps to Reproduce
1. On BSC Testnet, 23307800 is an epoch block. Verify that validator address "0x049153b8DAe0a232Ac90D20C78f1a5D1dE7B7dc5" is not present in the validator set.
2. Verify that "0x049153b8DAe0a232Ac90D20C78f1a5D1dE7B7dc5" is specified in previous epoch by checking previous epoch block 23307600
3. Verify that block 23307802 is validated by this removed validator "0x049153b8DAe0a232Ac90D20C78f1a5D1dE7B7dc5"
4. Similar behavior can be seen on block 20954003 which is validated by "0x6d6247501b822FD4Eaa76FCB64bAEa360279497f", which was removed in current epoch block

## Expected Behavior
BSC Verifier should update validator set at the block in which BSC chain does. [Docs](https://docs.bnbchain.org/docs/learn/consensus#light-client-security) specify that the change is delayed by N/2 blocks where N is the number of validators in the previous epoch.

## Proposed Solution
Update Verifier struct to save validatorSet for both previous and current epoch as well as the specific height from which new validator set will be used to verify header. That height will be calculated as epochHeight + (prevValidatorCount/2) + 1
Example: 
prevValidatorCount = 7, epochHeight = 22502200, useNewValidatorFromHeight=22502204
prevExistingValidator = "0x6d6247501b822FD4Eaa76FCB64bAEa360279497f"
BlockValidatedByPreviouslyExistingValidator = 22502203

### PR DESCRIPTION
**Pull request by manishbista28**
Closes #575 

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the unit tests
- [x] I only have one commit (if not, squash them into one commit).
- [x] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

### CODE REVIEW

File: cmd/iconbridge/chain/bsc/verifier.go [hunk 1]
```diff
@@ -166,7 +174,9 @@ func (vr *Verifier) Update(header *types.Header) (err error) {
 			return errors.Wrapf(err, "getValidatorMapFromHex %v", err)
 		}
 		// update validators only if epoch block and no error encountered
+		vr.prevValidators = vr.validators
 		vr.validators = newValidators
+		vr.useNewValidatorsFromHeight = (&big.Int{}).Add(header.Number, big.NewInt(1+int64(len(vr.prevValidators)/2)))
```
Comment (bbist) [inline cmd/iconbridge/chain/bsc/verifier.go:179]: Does this height need to be explicitly computed, or is the height part of some block data in the block where a validators change happens? If it's part of block data, then using the height from it instead of computing it manually is better. Otherwise, it's okay.

**Review by bbist — APPROVED** [review]
Looks good.
