### PR TITLE
fix(bts): update get_token_limit to public method

### LINKED ISSUE #589: Method is private for getting token limit value in BTS
## Overview
Methods is private for getting token limit value in BTS

## Steps to Reproduce
Steps to reproduce the behaviour:
1. In near cli 
2. Run the query call to the bts contract
3. With methods `get_token_limit` 
4. Method not found error will be thrown

## Expected Behavior
When we query `get_token_limit`  method we should get the token limit value for that respective token

## Screenshots
MicrosoftTeams-image (3)

## Device Information

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

### PR DESCRIPTION
**Pull request by shreyasbhat0**
Closes #589 

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have run the unit tests
- [x] I only have one commit (if not, squash them into one commit).
- [ ] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

### CODE REVIEW

File: rust/near/bsh/bts/tests/test_coin_management.rs [hunk 1]
```diff
@@ -213,8 +208,8 @@ fn update_token_limit() {
     let limits = vec![10000000000000000000003_u128];
     contract.set_token_limit(coins, limits).unwrap();
 
-    let tokenlimits = contract.get_token_limit().get("NEAR").unwrap();
-    assert_eq!(tokenlimits, &10000000000000000000003_u128)
+    let tokenlimits = contract.get_token_limit("NEAR".to_string());
+    assert_eq!(tokenlimits, 10000000000000000000003_u128)
```
Comment (MuhammedIrfan) [inline rust/near/bsh/bts/tests/test_coin_management.rs:212]:
```suggestion
    let token_limits = contract.get_token_limit("NEAR".to_string());
    assert_eq!(token_limits, 10000000000000000000003_u128)
```

File: rust/near/bsh/bts/tests/test_coin_management.rs [hunk 2]
```diff
@@ -185,16 +184,12 @@ fn set_token_limit() {
     let coins = vec!["NEAR".to_string()];
     let limits = vec![10000000000000000000000_u128];
     contract.set_token_limit(coins, limits).unwrap();
-    let tokenlimits = contract.get_token_limit();
+    let tokenlimits = contract.get_token_limit("NEAR".to_string());
```
Comment (MuhammedIrfan) [inline rust/near/bsh/bts/tests/test_coin_management.rs:187]:
```suggestion
    let token_limits = contract.get_token_limit("NEAR".to_string());
```

File: rust/near/bsh/bts/tests/test_coin_management.rs [hunk 3]
```diff
@@ -185,16 +184,12 @@ fn set_token_limit() {
...
 
-    assert_eq!(
-        tokenlimits.get("NEAR").unwrap(),
-        &10000000000000000000000_u128
-    )
+    assert_eq!(tokenlimits, 10000000000000000000000_u128)
```
Comment (MuhammedIrfan) [inline rust/near/bsh/bts/tests/test_coin_management.rs:189]:
```suggestion
    assert_eq!(token_limits, 10000000000000000000000_u128)
```

**Review by MuhammedIrfan — APPROVED** [review]
